# server port config
server:
  port: 8100
  
# oracle driver config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver 
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: health_dao
    password: health_dao
  
# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml 
  
custom:
  path:
# 상훈 pc
#   upload-images: 'D:/develop/boot_workspace/HealthDAO/src/main/resources/uploadFiles/'
# 상훈 노트북
    upload-images: 'D:/spring/final/HealthDAO/src/main/resources/uploadFiles/'